/**
 * @readonly
 * @enum
 */
const ERROR_CODE = {
  AUTHERR: 'AUTHORIZATION_ERROR',
  NOAUTHERR: 'MISSING_AUTHORIZATION',
  INVLDAUTHTOKEN: 'INVALID_AUTH_TOKEN',
  INACTIVEACCT: 'INACTIVE_ACCOUNT',
  EXPIREDTOKEN: 'EXPIRED_TOKEN',
  INVLDREQ: 'INVALID_REQUEST',
  PERMERR: 'PERMISSION_ERROR',
  LIMITERR: 'LIMIT_ERROR',
  FEEERR: 'FEE_ERROR',
  NOTFOUND: 'RESOURCE_NOT_FOUND',
  APPERR: 'APPLICATION_ERROR',
  HTTPREQERR: 'INTERNAL_REQ_ERROR',
  DUPLRCRD: 'DUPLICATE_RECORD',
  VALIDATIONERR: 'VALIDATION_ERROR',
  INVLDDATA: 'INVALID_REQUEST_DATA',
  RTLIMERR: 'RATE_LIMIT_ERROR',
  SL01: 'SLUG_ALREADY_TAKEN',
  AC01: 'ACCESS_CODE_REQUIRED',
  AC04: 'ACCESS_CODE_ON_PUBLIC_CARD',
  NF01: 'SLUG_NOT_FOUND',
  NF02: 'CARD_IN_DRAFT_STATUS',
  AC03: 'ACCESS_CODE_REQUIRED_FOR_PRIVATE_CARD',
  AC04: 'ACCESS_CODE_INCORRECT',
  NF03: 'CARD_ALREADY_DELETED',
};

const ERROR_STATUS_CODE_MAPPING = {
  AUTHORIZATION_ERROR: 401,
  MISSING_AUTHORIZATION: 401,
  INVALID_AUTH_TOKEN: 401,
  INACTIVE_ACCOUNT: 401,
  EXPIRED_TOKEN: 401,
  PERMISSION_ERROR: 401,
  INVALID_REQUEST: 403,
  LIMIT_ERROR: 403,
  FEE_ERROR: 403,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_RECORD: 409,
  APPLICATION_ERROR: 500,
  RATE_LIMIT_ERROR: 429,
  SLUG_ALREADY_TAKEN: 400,
  ACCESS_CODE_REQUIRED: 400,
  ACCESS_CODE_ON_PUBLIC_CARD: 400,
  SLUG_NOT_FOUND: 404,
  CARD_IN_DRAFT_STATUS: 404,
  ACCESS_CODE_REQUIRED_FOR_PRIVATE_CARD: 403,
  ACCESS_CODE_INCORRECT: 403,
  CARD_ALREADY_DELETED: 404,
};

module.exports = { ERROR_CODE, ERROR_STATUS_CODE_MAPPING };
